tickers:
  - AAPL
  - MSFT
  - GOOG
  - AMZN
  - META
rsi_threshold: 70

backtest_start: "2023-01-01"
backtest_end: "2024-01-01"

order:
  mode: local   # dummy | local | real
  exit_rule: rsi  # rsi | なし（将来: hold_days, stop_loss などもOK）
