name: Run Investment Bot Daily

on:
  schedule:
    - cron: "0 23 * * *"  # 毎日8:00 JST（23:00 UTC）
  workflow_dispatch:      # 手動実行も可能

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GCP_CREDENTIALS_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Japanese font (VL Gothic)
        run: sudo apt-get install -y fonts-vlgothic

      - name: Write GCP credentials file
        run: |
            echo "$GCP_CREDENTIALS_B64" | base64 --decode > credentials.json

      - name: Run main.py
        run: |
          python main.py
